package com.campusvote.service;
import com.campusvote.dto.*; import com.campusvote.model.*; import com.campusvote.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service public class ElectionService {
 final ElectionRepository er; final PostRepository pr; final CandidateRepository cr; final UserRepository ur; final VoteRepository vr;
 public ElectionService(ElectionRepository er,PostRepository pr,CandidateRepository cr,UserRepository ur,VoteRepository vr){this.er=er;this.pr=pr;this.cr=cr;this.ur=ur;this.vr=vr;}
 public Map<String,Object> login(LoginRequest q){User u=ur.findByStudentId(q.studentId()).orElseThrow(()->new RuntimeException("Invalid ID or password")); if(!u.isActive()||!u.getPassword().equals(q.password()))throw new RuntimeException("Invalid ID or password"); return user(u);}
 @Transactional public Election create(CreateElectionRequest q){if(q.endTime()==null||q.startTime()==null||!q.endTime().isAfter(q.startTime()))throw new RuntimeException("End time must be after start time"); Election e=new Election();e.setTitle(q.title());e.setDescription(q.description());e.setStartTime(q.startTime());e.setEndTime(q.endTime());for(String n:q.posts()){if(n!=null&&!n.isBlank()){Post p=new Post();p.setName(n.trim());p.setElection(e);e.getPosts().add(p);}}return er.save(e);}
 public Candidate addCandidate(Long postId,AddCandidateRequest q){Post p=pr.findById(postId).orElseThrow(()->new RuntimeException("Post not found"));Candidate c=new Candidate();c.setName(q.name());c.setManifesto(q.manifesto());c.setDepartment(q.department());c.setYear(q.year());c.setPhotoUrl(q.photoUrl());c.setPost(p);return cr.save(c);}
 public List<Map<String,Object>> all(){return er.findAll().stream().sorted(Comparator.comparing(Election::getStartTime).reversed()).map(this::map).toList();}
 public Map<String,Object> one(Long id){return map(er.findById(id).orElseThrow(()->new RuntimeException("Election not found")));}
 @Transactional public void vote(VoteRequest q){User s=ur.findById(q.studentId()).orElseThrow(()->new RuntimeException("Student not found")); if(s.getRole()!=User.Role.STUDENT)throw new RuntimeException("Only students can vote");if(q.candidateIds()==null||q.candidateIds().isEmpty())throw new RuntimeException("Select candidates");Set<Long> posts=new HashSet<>();List<Candidate> selected=new ArrayList<>();for(Long cid:q.candidateIds()){Candidate c=cr.findById(cid).orElseThrow(()->new RuntimeException("Candidate not found"));Post p=c.getPost();Election e=p.getElection();LocalDateTime n=LocalDateTime.now();if(n.isBefore(e.getStartTime())||n.isAfter(e.getEndTime()))throw new RuntimeException("Voting is not open");if(!posts.add(p.getId()))throw new RuntimeException("Select only one candidate per post");if(vr.existsByStudentIdAndPostId(s.getId(),p.getId()))throw new RuntimeException("Already voted for "+p.getName());selected.add(c);}for(Candidate c:selected)vr.save(new Vote(s,c.getPost(),c));}
 public Map<String,Object> status(Long eid,Long sid){Election e=er.findById(eid).orElseThrow();List<Long> ids=vr.findByStudentId(sid).stream().filter(v->v.getPost().getElection().getId().equals(eid)).map(v->v.getPost().getId()).toList();return Map.of("votedPostIds",ids,"totalPosts",e.getPosts().size());}
 public List<Map<String,Object>> results(Long id){Election e=er.findById(id).orElseThrow();if(LocalDateTime.now().isBefore(e.getEndTime()))throw new RuntimeException("Results are available after voting closes");return e.getPosts().stream().map(p->{Map<String,Object> x=new LinkedHashMap<>();x.put("postId",p.getId());x.put("postName",p.getName());x.put("candidates",p.getCandidates().stream().map(c->{Map<String,Object> y=new LinkedHashMap<>();y.put("candidateId",c.getId());y.put("name",c.getName());y.put("department",c.getDepartment());y.put("voteCount",vr.countByCandidateId(c.getId()));return y;}).sorted((a,b)->Long.compare((Long)b.get("voteCount"),(Long)a.get("voteCount"))).toList());return x;}).toList();}
 Map<String,Object> user(User u){Map<String,Object> m=new LinkedHashMap<>();m.put("id",u.getId());m.put("studentId",u.getStudentId());m.put("name",u.getName());m.put("email",u.getEmail());m.put("role",u.getRole());m.put("department",u.getDepartment());return m;}
 Map<String,Object> map(Election e){Map<String,Object> m=new LinkedHashMap<>();m.put("id",e.getId());m.put("title",e.getTitle());m.put("description",e.getDescription());m.put("startTime",e.getStartTime());m.put("endTime",e.getEndTime());m.put("posts",e.getPosts().stream().map(p->{Map<String,Object>x=new LinkedHashMap<>();x.put("id",p.getId());x.put("name",p.getName());x.put("candidates",p.getCandidates().stream().map(c->{Map<String,Object>y=new LinkedHashMap<>();y.put("id",c.getId());y.put("name",c.getName());y.put("manifesto",c.getManifesto());y.put("department",c.getDepartment());y.put("year",c.getYear());y.put("photoUrl",c.getPhotoUrl());return y;}).toList());return x;}).toList());return m;}
}
